pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/bin/apache-maven"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/ravdy/javaloginapp.git'
            }
       }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
       }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'SonarScanner 4.0';
        steps{
            withSonarQubeEnv('SonarQube-9.2.4') { 
                sh "mvn sonar:sonar"
            }
        }
        }
       
    }
}
